# Data Science intern @CipherByte Technologies

# TASK - 2: Spam Email Detection

In [79]:
# import library files
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter('ignore')

In [80]:
# Load data file
data=pd.read_csv('email spams.csv', encoding='latin-1')

In [81]:
data.head()

title                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [82]:
data.shape

(1339, 2)

In [83]:
data.describe()

title                 Message
count   1339                    1339
unique     2                    1297
top      ham  Sorry, I'll call later
freq    1143                       8

In [84]:
data.isnull().sum()

title      0
Message    0
dtype: int64

In [85]:
data.nunique()

title         2
Message    1297
dtype: int64

In [86]:
data.rename(columns = {"title" : "Spam or Ham"},inplace = True)
data

Spam or Ham                                            Message
0            ham  Go until jurong point, crazy.. Available only ...
1            ham                      Ok lar... Joking wif u oni...
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...
3            ham  U dun say so early hor... U c already then say...
4            ham  Nah I don't think he goes to usf, he lives aro...
...          ...                                                ...
1334         ham         Oh... Icic... K lor, den meet other day...
1335         ham  Oh ! A half hour is much longer in Syria than ...
1336         ham  Sometimes we put walls around our hearts,not j...
1337         ham  Sweet, we may or may not go to 4U to meet carl...
1338         ham       Then she buying today? Ü no need to c meh...

[1339 rows x 2 columns]

In [87]:
# Converting the categorical values into numerical values
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['Spam or Ham'] = encoder.fit_transform(data['Spam or Ham'])

In [88]:
#Finding duplicates
data.duplicated().sum()

42

In [89]:
data = data.drop_duplicates(keep = 'first')
data.duplicated().sum()

0

In [90]:

! pip3 install scikit-learn

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [91]:
#Splitting the data
X = data["Message"]
Y = data["Spam or Ham"]

In [92]:
print(X)
print(Y)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
1334           Oh... Icic... K lor, den meet other day...
1335    Oh ! A half hour is much longer in Syria than ...
1336    Sometimes we put walls around our hearts,not j...
1337    Sweet, we may or may not go to 4U to meet carl...
1338         Then she buying today? Ü no need to c meh...
Name: Message, Length: 1297, dtype: object
0       0
1       0
2       1
3       0
4       0
       ..
1334    0
1335    0
1336    0
1337    0
1338    0
Name: Spam or Ham, Length: 1297, dtype: int32


In [93]:

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)


In [94]:
print(X.shape)
print(Y.shape)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)


(1297,)
(1297,)
(1037,)
(260,)
(1037,)
(260,)


In [95]:
data.nunique()

Spam or Ham       2
Message        1297
dtype: int64

In [96]:
print(X_train)


491     Sorry man my account's dry or I would, if you ...
695     Ah poop. Looks like ill prob have to send in m...
338                            Just sleeping..and surfing
306     Yup... From what i remb... I think should be c...
1045    We know someone who you know that fancies you....
                              ...                        
782     Hmmm ... I thought we said 2 hours slave, not ...
857                         Going to take your babe out ?
1256    Just wait till end of march when el nino gets ...
570                            WOT U WANNA DO THEN MISSY?
697     Aight, you close by or still down around alex'...
Name: Message, Length: 1037, dtype: object


In [97]:

# Convert the text data into a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [98]:
#Fitting Mutinomial naive bayes
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, Y_train)

MultinomialNB()

In [99]:
#Testing the mail(spam/ham)

mail_ham = ['Same. Wana plan a trip sometme then']
mail_ham_count = cv.transform(mail_ham)
y_pred = model.predict(mail_ham_count)
y_pred

array([0])

In [100]:
#finding accuracy of the training dataset
model.score(X_train_count, Y_train)

0.9951783992285439

In [101]:
#finding accuracy of thr test dataset
X_test_count = cv.transform(X_test)
model.score(X_test_count, Y_test)

0.9807692307692307

In [105]:
# Evaluate the model
confusion = confusion_matrix(Y_test, y_pred)

print(f"Confusion Matrix:\n{confusion}")


Confusion Matrix:
[[225   0]
 [ 17  18]]
